Arrays: Sequence of adjacent memory locations assinged in a single variable:
- complex data type - built from group of simple data types like int, char, float etc.
- int arrays - [1,2,3,4,5]
- char arrays - ['a','b','c','d']
- float arrays - [1.2,3.67,3.4,9.6,6.578]

```arr = [0,1,2,3,4,5]```

Array indicies starts from 0 till N-1 where N is the length of the Array.

Arrays will consume less memory for similar data as compared to a list/tupple.

NumPy - library/packages to process such arrays/complex numeric types.

ILATE - Inverse/Imaginary Logarithmic Algebric Trignometric Exponencial

Matrix computations can also be done in numpy 


Why NumPy?
- NumPy has already things coded for you to directly use and its 50x faster than traditional list processing in python.
- Faster because it is not producing any object directly producing memory sequences with raw data.
- Locality of reference: adjacent memory locations
- NumPy is written in C/C++ | runs directly on hardware.

The code is available at https://github.com/numpy/numpy

PIP - Python Index package | App/Win/Play Store for python | Package Manager

Anaconda - IDE - NumPy comes pre-installed

Install NumPy: ```$> pip3 install numpy``` 

pip3 is installed at: C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python<VERSION>\Scripts\pip3.exe | add this to PATH variable in your System Env Variables

Importing NumPy: import numpy as np

In [2]:
import numpy as np  # import NumPy Library in to runtime env | np is called 'alias'

In [2]:
np.__version__  # checking version for any packages

'1.20.3'

In [9]:
arr = np.array([1,2,3,4,5])  # initialize a numpy arr

print(arr)

print(type(arr))  # to check the type of the class for the given object

print(arr.shape)  # to check the shape of the arr | *shape* given info about rows and cols, helpful in matrix algebra
print(arr.ndim)  # to check the dimentions of the arr

arr2d = np.array([[1,2,3],[4,5,6]]) # initialize a 2D arr

print(arr2d)
print(arr2d.shape) # to check the shape of the arr
print(arr2d.ndim) # to check the dimentions of the arr

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1
[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [12]:
# creating a 3D Array using NumPy

arr_3d = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[0,1,2]]
])

print(f" 3D Array: \n{arr_3d}")
print(f" \nDimension: {arr_3d.ndim}")
print(f" Shape: {arr_3d.shape}")

 3D Array: 
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 2]]]
 
Dimension: 3
 Shape: (2, 2, 3)


To increase the dimentions, you can do nesting on your lists

In [22]:
# using dimesion to genertate N-dimensional arrays

arr = np.array([1,2,3,4], ndmin=2)
print(arr)
print(arr.reshape((2,2)))  # to change the shape of the array | *NEED* to only provide the shape with matches the number of elements in the array
print(type(arr))  # to check the type of the class for the given object
print(arr.shape)  # to check the shape of the arr | *shape* given info about rows and cols, helpful in matrix algebra
print(arr.ndim)  # to check the dimentions of the arr

[[1 2 3 4]]
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
(1, 4)
2


In [24]:
# Accessing the elements of an array
arr = [1,2,3,4,5,6,7]
print(arr[5])
for i in range(len(arr)):
    print(arr[i])

6
1
2
3
4
5
6
7


In [37]:
# 2d Array access to elements

arr = np.array([[1,2,3],[3,4,2]])  # list of list

print(arr)
print(arr[0][1])
print(arr.shape)

# Iterating over a 2d arr using loop
for row in range(arr.shape[0]):
    for col in range(arr.shape[1]):
        print(arr[row][col])
        
print(len(arr))
print(arr[0])
43431 X 1500
print(arr[0,9])  # arr[ROW,COL] | ROW & COL start from 0

# Arrays and NumPy Arrays are different

[[1 2 3]
 [3 4 2]]
2
(2, 3)
1
2
3
3
4
2
2
[1 2 3]
4


# Array Slicing

In [10]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[3:8:1])  # 3 - starting index | 8 - end index | 1 - step size
print(arr[3:8:2])

print(arr[::2]) # iterate alternate indecies

[4 5 6 7 8]
[4 6 8]
[1 3 5 7 9]


In [20]:
for i in range(4):
    print(i)

0
1
2
3


In [22]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[26,27,28,29,30]])

print(arr)
print()
print(arr[1:4,])  # [ROW_SLICE_RANGE,COL_SLICE_RANGE]
print()
print(arr[1:4,1:3])  # [ROW_SLICE_RANGE,COL_SLICE_RANGE]
print(arr[1::2,1:3])  # Step size can also be configured in N-Dimensional Arrays

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [26 27 28 29 30]]

[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 7  8]
 [12 13]
 [17 18]]


# DataTypes in NumPy

- Strings e.g. 'ABC'
- Integers e.g. 1
- float e.g. 5.98
- boolean e.g. True
- complex e.g. 1.0 + 2.0j

### Data Type Codes

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [25]:
arr = np.array([1,2,3,4])
    
print(arr.dtype)  # int32

arr = np.array(['dogs','cats','horses'], dtype='S')  # to initalize with a specific datatype

print(arr.dtype)

int32
|S6


In [42]:
# In class discusions

import datetime as dt

print(dt.datetime.now())

date = '2022-01-03 12:03:56'

print(date)
print(type(date))

date = dt.datetime.fromisoformat(date)

print(date.hour)
print(type(date))

print(dt)
print(dt.datetime)
print(dt.datetime.now)
print(np)
print(np.array)

2022-02-11 20:38:12.596129
2022-01-03 12:03:56
<class 'str'>
12
<class 'datetime.datetime'>
<module 'datetime' from 'C:\\Users\\sauve\\anaconda3\\lib\\datetime.py'>
<class 'datetime.datetime'>
<built-in method now of type object at 0x00007FF8C9013650>
<module 'numpy' from 'C:\\Users\\sauve\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
<built-in function array>


In [52]:
class triangle:
    def __init__(self,a,b,c):
        self.side1 = a
        self.side2 = b
        self.side3 = c
        
    def perimeter(self):
        return self.side1 + self.side2 + self.side3
    
    def greet():
        return "Thanks for calling me"
    

def perimeter(a,b,c):
    return a + b + c

In [53]:
t1 = triangle(2,3,4)
t2 = triangle(5,8,9)

print(t1.side2)
print(t1.perimeter())

print(perimeter(2,3,4))

print(t2.side2)
print(t2.perimeter())
print(triangle.greet())

3
9
9
8
22
Thanks for calling me


In [54]:
arr = np.array([1.1,3.3,2.4])

arr1 = arr.astype('i')  # typecasting / parsing into another data type

print(arr)
print(arr1)

[1.1 3.3 2.4]
[1 3 2]


In [57]:
# np arrays aslo refer to the same memory location if we assign them as below:

arr1 = np.array([1,2,3,4,5])
arr2 = arr1

print(arr1)
print(arr2)

arr2[1] = 275

print(arr1)
print(arr2)

# to create a new array object in the memory, we can use copy()

arr1 = np.array([1,2,3,4,5])
arr2 = arr1.copy()

print(arr1)
print(arr2)

arr2[1] = 275

print(arr1)
print(arr2)


[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[  1 275   3   4   5]


In [58]:
arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr)

arr1 = arr.reshape(3,3)  # to change the shape of an array

print(arr1)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [59]:
arr = np.array([1,2,3,4,4,5,5,6])

for element in arr:  # iterating on arrays
    print(element)

1
2
3
4
4
5
5
6


In [62]:
arr1 = np.array([1,2,3,4,5])

arr2 = np.array([6,7,8,9])

arr = np.concatenate((arr2,arr1))  # join two arrays

print(arr1)
print(arr2)
print(arr)

[1 2 3 4 5]
[6 7 8 9]
[6 7 8 9 1 2 3 4 5]


In [72]:
arr1 = np.array([1,2,3,4,5])

arr2 = np.array([6,7,8,9])

arr = np.concatenate((arr2,arr1))  # join two arrays

narr = np.array_split(arr,14)

print(arr1)
print(arr2)
print(arr)
print(narr)

[1 2 3 4 5]
[6 7 8 9]
[6 7 8 9 1 2 3 4 5]
[array([6]), array([7]), array([8]), array([9]), array([1]), array([2]), array([3]), array([4]), array([5]), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32)]


In [70]:
# Search in arrays

arr = np.array([1,2,3,4,5])

arr1 = np.where(arr >= 6)

print(arr1)

(array([], dtype=int64),)


In [88]:
arr = np.array([33,55,47,84,2])

# The searchsorted() method is assumed to be used on sorted arrays.

x = np.searchsorted(arr,7,side='right')

print(x)

0


In [91]:
arr1 = np.array([6,7,3,4,6,6,6,77,77,11])
x= np.searchsorted(arr1,67)
print(x)

print(np.sort(arr1))

print(-np.sort(-arr1))


7
[ 3  4  6  6  6  6  7 11 77 77]
[77 77 11  7  6  6  6  6  4  3]
